version: '3.9'

services:
  postgres-nest:
    image: postgres:alpine
    container_name: postgres-nest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task-management
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=nest@udemy.com.br
      - PGADMIN_DEFAULT_PASSWORD=course1234
    restart: always
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/root/.pgadmin

  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    restart: always
    ports:
      - '8080:8000'
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
  postgres_data:
  pgadmin_data:
