version: '3.9'

services:
  mongo-nest:
    image: mongo:latest
    container_name: mongo-nest
    ports:
      - '27017:27017'

  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    restart: always
    ports:
      - '8080:8000'
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
  postgres_data:
  pgadmin_data:
